services:
  db:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5437:5432

  siwapp:
    build:
      context: .
      args:
        user_id: ${UID:-1000}
      dockerfile: docker/Dockerfile
    command: elixir -S mix phx.server
    depends_on:
      - db
    entrypoint: [ "./docker/entrypoint.sh" ]
    environment:
      DB_HOST: db
      MIX_ENV: dev
    ports:
      - "4010:4000"
    volumes:
      - ${PWD}:/app
version: '3'
